# Generated by Django 2.2 on 2019-10-20 21:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0002_profilefeeditem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilefeeditem',
            old_name='uder_profile',
            new_name='user_profile',
        ),
        migrations.AddField(
            model_name='profilefeeditem',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profilefeeditem',
            name='status_text',
            field=models.CharField(default='e', max_length=255),
            preserve_default=False,
        ),
    ]
